### ISSUE TITLE
Unable to load games with latest core and latest RA version

### ISSUE THREAD

**Issue by PhobosAnomaly666** [libretro/px68k-libretro#151] opened 2021-10-24 16:03 UTC
Hello there,

I've upgraded my RA installation after a good year (or more) without touching it, all went fine and I was trying my different systems to see if things were correctly working after this, everything seems fine but I'm struggling with x68000 for some reason: games just do not start anymore.

I've checked other issues reporting the same issues I have (black screen after launch, no music, no picture, nothing loads, I can only display the core menu using F12), nothing helped me to understand what went wrong.

I backed up my old installation just in case, and tried using the old core version that was working, on my updated RA install: it's working with the old one, which is this version:

https://i.imgur.com/Jujyoii.png

Latest core downloaded from buildbot, no luck...

I only got three games to use, Akumajou Dracula, Thunder Force II and Downtown Nekketsu, both are setup to load using .m3u files, correctly formated with only file names in it.

Everything's ok with the old core, it's just the new one, for some reason, that doesn't work.

What happened and did I miss something after all these updates ? What could be the reason ?

Thank you for the help !!

**Comment by PhobosAnomaly666** [comment] 2021-11-01 10:47
Hey ! Sorry for the delay, thanks for your answers so far.

Yes, the core I've been using and working is probably from early 2020 if I'm correct, last time I updated my RA installation before the past week.

At least the problem is not on my side, I hope you'll be able to find a solution for this. I have no technical knowledge but if you may need more informations, I'll do whatever I can !

**Comment by ToniBC** [comment] 2021-11-08 17:00
Apparently according to comments in the notes of version 1.9.13, they are adapting things, hopefully the core works again, because I tried the latest version and it still crashes in Windows 10 x64.

**Comment by ToniBC** [comment] 2021-11-27 12:06
I put the log in case it helps, but the core still doesn't work.

```
[INFO] RetroArch 1.9.13 (Git 454fddb)
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Nov 27 2021
[INFO] Version: 1.9.13
[INFO] Git: 454fddb
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Core]: Loading dynamic libretro core from: "cores\px68k_libretro.dll"
[INFO] [Overrides]: No core-specific overrides found at "F:\Emuladores\RetroArch\config\PX68K\PX68K.cfg".
[INFO] [Overrides]: No content-dir-specific overrides found at "F:\Emuladores\RetroArch\config\PX68K\Temp.cfg".
[INFO] [Overrides]: No game-specific overrides found at "F:\Emuladores\RetroArch\config\PX68K\Active Shoot (1999)(Satou Kouji).cfg".
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] Controller port: 1
[INFO]    RetroPad (ID: 1)
[INFO]    RetroKeyboard (ID: 3)
[INFO] Controller port: 2
[INFO]    RetroPad (ID: 1)
[INFO]    RetroKeyboard (ID: 3)
[INFO] [Environ]: SET_SUPPORT_NO_GAME: yes.
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_INTL.
[INFO] [Remaps]: Remap directory: "F:\Emuladores\RetroArch\config\remaps".
[INFO] [Overrides]: Redirecting save file to "F:\Emuladores\RetroArch\saves\PX68K\Active Shoot (1999)(Satou Kouji).srm".
[INFO] [Overrides]: Redirecting save state to "F:\Emuladores\RetroArch\states\PX68K\Active Shoot (1999)(Satou Kouji).state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: SYSTEM_DIRECTORY: "F:\Emuladores\RetroArch\system".
[INFO] [Environ]: CORE_ASSETS_DIRECTORY: "F:\Emuladores\RetroArch\downloads".
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Environ]: GET_RUMBLE_INTERFACE.
[INFO] [Environ]: GET_DISK_CONTROL_INTERFACE_VERSION.
[INFO] [Environ]: SET_DISK_CONTROL_EXT_INTERFACE.
[INFO] [Environ]: GET_VARIABLE px68k_joytype1:
	Default (2 Buttons)
[INFO] [Environ]: GET_VARIABLE px68k_joytype2:
	Default (2 Buttons)
[INFO] [Environ]: GET_VARIABLE px68k_cpuspeed:
	10Mhz
[INFO] [Environ]: GET_VARIABLE px68k_ramsize:
	12MB
[INFO] [Environ]: GET_VARIABLE px68k_analog:
	disabled
[INFO] [Environ]: GET_VARIABLE px68k_adpcm_vol:
	15
[INFO] [Environ]: GET_VARIABLE px68k_opm_vol:
	12
[INFO] [Environ]: GET_VARIABLE px68k_disk_drive:
	FDD0
[INFO] [Environ]: GET_VARIABLE px68k_menufontsize:
	normal
[INFO] [Environ]: GET_VARIABLE px68k_joy1_select:
	Default
[INFO] [Environ]: GET_VARIABLE px68k_save_fdd_path:
	enabled
[INFO] [Environ]: GET_VARIABLE px68k_save_hdd_path:
	enabled
[INFO] [Environ]: GET_VARIABLE px68k_rumble_on_disk_read:
	disabled
[INFO] [Environ]: GET_VARIABLE px68k_joy_mouse:
	Mouse
[INFO] [Environ]: GET_VARIABLE px68k_vbtn_swap:
	TRIG1 TRIG2
[INFO] [Environ]: GET_VARIABLE px68k_no_wait_mode:
	disabled
[INFO] [Environ]: GET_VARIABLE px68k_frameskip:
	Full Frame
[INFO] [Environ]: GET_VARIABLE px68k_push_video_before_audio:
	disabled
[INFO] [Environ]: GET_VARIABLE px68k_adjust_frame_rates:
	enabled
[INFO] [Environ]: GET_VARIABLE px68k_audio_desync_hack:
	disabled
[INFO] [Environ]: SET_FRAME_TIME_CALLBACK.
[INFO] [CONTENT LOAD]: Content loading skipped. Implementation will load it on its own.
[libretro DEBUG] LOAD EMU

[INFO] [RCHEEVOS]: Load started, hardcore not active
[INFO] [RCHEEVOS]: Using host: https://retroachievements.org
[INFO] [RCHEEVOS]: Found 0 potential consoles for dim file extension
[INFO] [RCHEEVOS]: Trying console 4
[INFO] [RCHEEVOS]: Opened Active Shoot (1999)(Satou Kouji).dim
[INFO] [RCHEEVOS]: Hashing Active Shoot (1999)(Satou Kouji).dim (1261824 bytes)
[INFO] [RCHEEVOS]: Generated hash 83ab7f2837a0b97e172881924c759fd8
[INFO] [RCHEEVOS]: Attempting to login ToniBC (with token)
[INFO] [SRAM]: Skipping SRAM load.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 44144.14 Hz.
[INFO] [Video]: Video @ fullscreen
[INFO] [Vulkan]: Vulkan dynamic library loaded.
[INFO] [Vulkan]: Found vulkan context: vk_w
[INFO] [Vulkan]: Detecting screen resolution 1920x1080.
[INFO] [Vulkan]: Found GPU at index 0: NVIDIA GeForce GTX 970
[INFO] [Vulkan]: Using GPU index 0.
[INFO] [Vulkan]: Using GPU: NVIDIA GeForce GTX 970
[INFO] [Vulkan]: Queue family 0 supports 16 sub-queues.
[INFO] [Vulkan]: Using resolution 1920x1080
[INFO] [Vulkan]: Using RGB565 format.
[INFO] [Shaders]: Specific shader preset found at F:\Emuladores\RetroArch\config\PX68K\PX68K.slangp.
[DEBUG] [Shaders]:  Finding Parameters in Shader Passes (#pragma parameter)
[INFO] [slang]: Compiling shader "F:\Emuladores\RetroArch\shaders\shaders_slang\xbrz\shaders\6xbrz.slang".
[INFO] [slang]: Using render target format R8G8B8A8_UNORM for pass output #0.
[INFO] [slang]: Compiling shader "F:\Emuladores\RetroArch\shaders\shaders_slang\stock.slang".
[INFO] [Vulkan filter chain]: Creating framebuffer 6144 x 6144 (max 1 level(s)).
[INFO] [XInput]: Found XInput v1.4.
[INFO] [Joypad]: Found joypad driver: "dinput".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Video]: Found display server: win32
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Display]: Found display driver: "vulkan".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[DEBUG] [Shaders]:  Finding Parameters in Shader Passes (#pragma parameter)
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[libretro INFO] Set Controller Device: 1, Port: 0 1 0
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, Port 1, Button "B (bottom)" => "B"
[INFO] 	RetroPad, Port 1, Button "Y (left)" => "Y"
[INFO] 	RetroPad, Port 1, Button "Select" => "Select"
[INFO] 	RetroPad, Port 1, Button "Start" => "Start"
[INFO] 	RetroPad, Port 1, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, Port 1, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, Port 1, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, Port 1, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, Port 1, Button "A (right)" => "A"
[INFO] 	RetroPad, Port 1, Button "X (up)" => "X"
[INFO] 	RetroPad, Port 1, Button "L" => "L"
[INFO] 	RetroPad, Port 1, Button "R" => "R"
[INFO] 	RetroPad, Port 1, Button "L2" => "L2 - Menu"
[INFO] 	RetroPad, Port 1, Button "R2" => "R2"
[INFO] 	RetroPad, Port 1, Button "L3" => "L3"
[INFO] 	RetroPad, Port 1, Button "R3" => "R3"
[libretro INFO] Set Controller Device: 1, Port: 1 1 1
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] 	RetroPad, Port 1, Button "B (bottom)" => "B"
[INFO] 	RetroPad, Port 1, Button "Y (left)" => "Y"
[INFO] 	RetroPad, Port 1, Button "Select" => "Select"
[INFO] 	RetroPad, Port 1, Button "Start" => "Start"
[INFO] 	RetroPad, Port 1, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, Port 1, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, Port 1, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, Port 1, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, Port 1, Button "A (right)" => "A"
[INFO] 	RetroPad, Port 1, Button "X (up)" => "X"
[INFO] 	RetroPad, Port 1, Button "L" => "L"
[INFO] 	RetroPad, Port 1, Button "R" => "R"
[INFO] 	RetroPad, Port 1, Button "L2" => "L2 - Menu"
[INFO] 	RetroPad, Port 1, Button "R2" => "R2"
[INFO] 	RetroPad, Port 1, Button "L3" => "L3"
[INFO] 	RetroPad, Port 1, Button "R3" => "R3"
[INFO] 	RetroPad, Port 2, Button "B (bottom)" => "B"
[INFO] 	RetroPad, Port 2, Button "Y (left)" => "Y"
[INFO] 	RetroPad, Port 2, Button "Select" => "Select"
[INFO] 	RetroPad, Port 2, Button "Start" => "Start"
[INFO] 	RetroPad, Port 2, Button "D-Pad Up" => "Up"
[INFO] 	RetroPad, Port 2, Button "D-Pad Down" => "Down"
[INFO] 	RetroPad, Port 2, Button "D-Pad Left" => "Left"
[INFO] 	RetroPad, Port 2, Button "D-Pad Right" => "Right"
[INFO] 	RetroPad, Port 2, Button "A (right)" => "A"
[INFO] 	RetroPad, Port 2, Button "X (up)" => "X"
[INFO] 	RetroPad, Port 2, Button "L" => "L"
[INFO] 	RetroPad, Port 2, Button "R" => "R"
[INFO] 	RetroPad, Port 2, Button "L2" => "L2"
[INFO] 	RetroPad, Port 2, Button "R2" => "R2"
[INFO] 	RetroPad, Port 2, Button "L3" => "L3"
[INFO] 	RetroPad, Port 2, Button "R3" => "R3"
[DEBUG] [Shaders]:  Finding Parameters in Shader Passes (#pragma parameter)
[INFO] [Playlist]: Loading history file: [F:\Emuladores\RetroArch\content_history.lpl].
[INFO] [Playlist]: Loading history file: [F:\Emuladores\RetroArch\content_music_history.lpl].
[INFO] [Playlist]: Loading history file: [F:\Emuladores\RetroArch\content_video_history.lpl].
[INFO] [Playlist]: Loading history file: [F:\Emuladores\RetroArch\content_image_history.lpl].
[INFO] [Playlist]: Loading favorites file: [F:\Emuladores\RetroArch\content_favorites.lpl].
[INFO] [Vulkan filter chain]: Creating framebuffer 6144 x 6144 (max 1 level(s)).
[libretro DEBUG] Parsing arguments ...

[libretro DEBUG] 0 : px68k

[libretro DEBUG] 1 : F:\LaunchBox\ThirdParty\7-Zip\Temp\Active Shoot (1999)(Satou Kouji).dim

[libretro DEBUG] PX68K Ver."0.15+"

[libretro DEBUG] F:\Emuladores\RetroArch\system\keropi

[libretro DEBUG] cur_dir_str c:\ 3

[libretro DEBUG] fp:266506800 (iplrom.dat)

[libretro DEBUG] R: f800, G: 7e0, B: 1f

[libretro DEBUG] Restarting PX68K...

[libretro DEBUG] INIT done

[INFO] [Environ]: GET_VARIABLE px68k_joytype1:
	Default (2 Buttons)
[INFO] [Environ]: GET_VARIABLE px68k_joytype2:
	Default (2 Buttons)
[INFO] [Environ]: GET_VARIABLE px68k_cpuspeed:
	10Mhz
[INFO] [Environ]: GET_VARIABLE px68k_ramsize:
	12MB
[INFO] [Environ]: GET_VARIABLE px68k_analog:
	disabled
[INFO] [Environ]: GET_VARIABLE px68k_adpcm_vol:
	15
[INFO] [Environ]: GET_VARIABLE px68k_opm_vol:
	12
[INFO] [Environ]: GET_VARIABLE px68k_disk_drive:
	FDD0
[INFO] [Environ]: GET_VARIABLE px68k_menufontsize:
	normal
[INFO] [Environ]: GET_VARIABLE px68k_joy1_select:
	Default
[INFO] [Environ]: GET_VARIABLE px68k_save_fdd_path:
	enabled
[INFO] [Environ]: GET_VARIABLE px68k_save_hdd_path:
	enabled
[INFO] [Environ]: GET_VARIABLE px68k_rumble_on_disk_read:
	disabled
[INFO] [Environ]: GET_VARIABLE px68k_joy_mouse:
	Mouse
[INFO] [Environ]: GET_VARIABLE px68k_vbtn_swap:
	TRIG1 TRIG2
[INFO] [Environ]: GET_VARIABLE px68k_no_wait_mode:
	disabled
[INFO] [Environ]: GET_VARIABLE px68k_frameskip:
	Full Frame
[INFO] [Environ]: GET_VARIABLE px68k_push_video_before_audio:
	disabled
[INFO] [Environ]: GET_VARIABLE px68k_adjust_frame_rates:
	enabled
[INFO] [Environ]: GET_VARIABLE px68k_audio_desync_hack:
	disabled
[INFO] [RCHEEVOS]: ToniBC logged in successfully
[INFO] [RCHEEVOS]: Game could not be identified
[INFO] [Environ]: SET_SYSTEM_AV_INFO: 800x600, aspect: 1.333, fps: 59.940, sample rate: 44100.00 Hz.
[INFO] [Audio]: Set audio input rate to: 44144.14 Hz.
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Display]: Found display driver: "vulkan".
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Font]: Using font rendering backend: freetype.
[INFO] [Input]: Game Focus => OFF
[INFO] [Environ]: SET_FRAME_TIME_CALLBACK.
[libretro DEBUG] w:800 h:600 a:1.333

[libretro DEBUG] fps:59.94 soundrate:44100

[INFO] [Vulkan filter chain]: Creating framebuffer 6144 x 6144 (max 1 level(s)).
[libretro DEBUG] CPU Clock: 10MHz

[libretro DEBUG] RAM Size: 12MB
```

**Comment by Adancete23** [comment] 2021-12-06 13:44
Hello!

Still not working.Somebody is working on that?.

Thank you!.

**Comment by gingerbeardman** [comment] 2021-12-06 13:49
> Somebody is working on that?.

See 2 comments above yours: https://github.com/libretro/px68k-libretro/issues/151#issuecomment-963365916

**Comment by ToniBC** [comment] 2021-12-06 20:25
@twinaphex cleaned up the code and everything related to I/O, but the core is still broken, on PC at least, I don't know if the same thing happens on all devices, that would have to be confirmed, but on PC since 1.9 .11, the core does not load any game, but it does load the core.

That is, updating the cores and Retroarch, loading only the core, if we start it from the menu, face correctly, but then you can't load any game because it crashed.

**Comment by Adancete23** [comment] 2022-01-15 08:48
Hello!

Any news about this?.

Still not working

Thanks!.

**Comment by oraclespainpresales** [comment] 2022-01-27 13:33
Same error here 

[libretro DEBUG] PARAMCOUNT = 0

[libretro DEBUG] PX68K Ver."0.15+"

[libretro DEBUG] S:\portable\retroarch\system\keropi

[libretro DEBUG] cur_dir_str c:\ 3

[libretro DEBUG] fp:271018720 (iplrom.dat)

[libretro DEBUG] R: f800, G: 7e0, B: 1f

[libretro DEBUG] Restarting PX68K...

[libretro DEBUG] INIT done

[INFO] [Environ]: GET_VARIABLE: px68k_joytype1 = "Default (2 Buttons)"
[INFO] [Environ]: GET_VARIABLE: px68k_joytype2 = "Default (2 Buttons)"
[INFO] [Environ]: GET_VARIABLE: px68k_cpuspeed = "25Mhz"
[INFO] [Environ]: GET_VARIABLE: px68k_ramsize = "12MB"
[INFO] [Environ]: GET_VARIABLE: px68k_analog = "disabled"
[INFO] [Environ]: GET_VARIABLE: px68k_adpcm_vol = "15"
[INFO] [Environ]: GET_VARIABLE: px68k_opm_vol = "12"
[INFO] [Environ]: GET_VARIABLE: px68k_disk_drive = "FDD1"
[INFO] [Environ]: GET_VARIABLE: px68k_menufontsize = "normal"
[INFO] [Environ]: GET_VARIABLE: px68k_joy1_select = "Default"
[INFO] [Environ]: GET_VARIABLE: px68k_save_fdd_path = "enabled"
[INFO] [Environ]: GET_VARIABLE: px68k_save_hdd_path = "enabled"
[INFO] [Environ]: GET_VARIABLE: px68k_rumble_on_disk_read = "disabled"
[INFO] [Environ]: GET_VARIABLE: px68k_joy_mouse = "Mouse"
[INFO] [Environ]: GET_VARIABLE: px68k_vbtn_swap = "TRIG1 TRIG2"
[INFO] [Environ]: GET_VARIABLE: px68k_no_wait_mode = "disabled"
[INFO] [Environ]: GET_VARIABLE: px68k_frameskip = "Full Frame"
[INFO] [Environ]: GET_VARIABLE: px68k_push_video_before_audio = "disabled"
[INFO] [Environ]: GET_VARIABLE: px68k_adjust_frame_rates = "enabled"
[INFO] [Environ]: GET_VARIABLE: px68k_audio_desync_hack = "disabled"
[INFO] [Environ]: SET_SYSTEM_AV_INFO: 800x600, Aspect: 1.333, FPS: 59.94, Sample rate: 44100.00 Hz.
[INFO] [Audio]: Set audio input rate to: 44100.00 Hz.
[INFO] [XAudio2]: Requesting 64 ms latency, using 64 ms latency.
[INFO] [Display]: Found display driver: "vulkan".
[INFO] [Input]: Game Focus => OFF
[INFO] [Environ]: SET_FRAME_TIME_CALLBACK.
[libretro DEBUG] w:800 h:600 a:1.333

[libretro DEBUG] fps:59.94 soundrate:44100

[INFO] [Vulkan]: QueuePresent failed, destroying swapchain.
[INFO] [Environ]: SET_GEOMETRY: 0x0, Aspect: 1.333.
[libretro DEBUG] w:0 h:0 a:1.333

[libretro DEBUG] fps:59.94 soundrate:44100

[libretro DEBUG] CPU Clock: 25MHz

[libretro DEBUG] RAM Size: 12MB

Someting related to VULKAN driver???

**Comment by oraclespainpresales** [comment] 2022-01-27 13:51
I test it with Dx11 and GL CORE and same result :(

**Comment by gingerbeardman** [comment] 2022-01-27 21:41
@Adancete23 can you use the old core posted further up?

**Comment by Adancete23** [comment] 2022-02-01 15:47
Hello!

Yes, well Im using Windows and I tried to use an old version of this core, but its not working for me.

Thanks anyway.

**Comment by ToniBC** [comment] 2022-02-01 16:42
It works for everyone, you just have to download the 1.9.11 cores from the buildbot and replace only the px68k core, then go into Retroarch and protect it and create a backup for the future and nothing else.

**Comment by Adancete23** [comment] 2022-02-02 08:46
> Funciona para todos, solo tiene que descargar los núcleos 1.9.11 del buildbot y reemplazar solo el núcleo px68k, luego ingresar a Retroarch y protegerlo y crear una copia de seguridad para el futuro y nada más.

Perfecto Toni gracias.No lo entendía, ahora funciona con tu explicación, Gracias!!

**Comment by n1ghttrap** [comment] 2022-04-05 02:03
Update?

**Comment by gingerbeardman** [comment] 2022-04-05 08:41
> Update?

Use an old core.

**Comment by ToniBC** [comment] 2022-04-05 10:06
It is strange that the broken core continues, since the problem seems easy to solve, since it is a loading problem. But at the moment it seems that nobody looked at it yet.

This means that everyone who downloads it doesn't work for them and if they don't know how to look around here or the forum, they won't get it.

**Comment by gingerbeardman** [comment] 2022-04-05 11:12
@ToniBC you are 100% correct, sadly this is the state of many cores for some platforms on RA. There is no automated testing, there is no priority. It's really unfortunate.

The best we can do is use what we have that works.

**Comment by energy-t** [comment] 2022-08-14 01:16
Can someone with a windows build env test out my branch for me to see if it fixes this issue?  Find it here: https://github.com/energy-t/px68k-libretro/tree/musashi
I'm going to post this message in all 3 issues opened up for this issue, not trying to spam just looking for assistance from the various ppl reporting it

**Comment by ToniBC** [comment] 2022-08-14 09:47
@energy-t Because you don't compile the core, you put it in your GIT in releases so we can test it and stuff. It's complicated if you want users to compile the core themselves to test it.

**Comment by gouchi** [comment] 2022-08-15 08:14
Hi,

The core should be available on buildbot now, otherwise you can get the build directly for [i686](https://git.libretro.com/libretro/px68k-libretro/-/jobs/2367013/artifacts/download) or [x86_64](https://git.libretro.com/libretro/px68k-libretro/-/jobs/2367012/artifacts/download). 

@PhobosAnomaly666 The title of the issue should be renamed to something more  accurate for example `Can't load content any more with px68k libretro core on Windows`.

If the issue is fixed after testing please close it.

Thank you.

**Comment by ToniBC** [comment] 2022-08-15 13:17
The core downloaded from buildbot seems to be working fine now, so the boot issue seems to be fixed.

**Closed** 2022-08-18 17:58 UTC
