### ISSUE TITLE
'Star Mobile' Crashes px68k core

### ISSUE THREAD

**Issue by McRmie** [libretro/px68k-libretro#163] opened 2022-11-06 19:49 UTC
After starting the game, you see a rotating 'MNM' logo, after that the game loads some more from the disk and that's when the crash occurs (crashes the core and RA). Tried different CPU speeds and amount of RAM; same results. 

Tried to play the game in MAME but no luck either. Doesn't even reach the spinning logo, just shows a message in Japanese -"バスエラ/basuera"-something ("Bus Error" I guess). The game loads and plays fine in XM6 Pro 68k.

The disk image's sha1 is: 011afd5f444edb8ed7b2a117eb3e4ba4545a504f same as MAME x68k_flop hash file.

edit:
update - Got the game working in MAME. Had to disable "Enable Fake Bus Error" in the Machine Configuration (was ON by default). 

One thing I noticed is after you see the company's logo animation is that there is a resolution change. During the logo animation MAME indicates the game runs at [256x512](https://i.imgur.com/lzZtKrK.png) and after that it switches to [512x512](https://i.imgur.com/tpfKDp3.png). Then after that it goes back to 256x512 once more.

So maybe the crash is related to that resolution switch.

**Comment by LibretroAdmin** [comment] 2022-11-25 06:34
Thanks a lot for this advice @TurtleBazooka -

I have implemented it here and given you credit. Hope that fixes this game and the OP can confirm.
https://github.com/libretro/px68k-libretro/commit/b981615516eea8a465c6d060cc19beb11a369b85

Great fork you are running BTW :)

**Comment by LibretroAdmin** [comment] 2022-11-26 03:17
@McRmie Can you confirm if the issue is now fixed for you?

**Comment by McRmie** [comment] 2022-11-26 21:02
Just tested on the latest build (0.15+ 7d78615) and the issue is indeed resolved. Big thanks to TurtleBazooka for the fix.

**Closed** 2022-11-26 21:31 UTC

**Comment by LibretroAdmin** [comment] 2022-11-27 01:53
Awesome to hear! Thanks for helping us @TurtleBazooka .
