### ISSUE TITLE
[macOS] Black Screen

### ISSUE THREAD

**Issue by gingerbeardman** [libretro/px68k-libretro#121] opened 2020-01-24 18:39 UTC
From #32

Log, with verbose debug logging turned on. Here, I try loading a disk `Akazukin Cha Cha Cha v1.04 (1995)(Sprite).dim` through frontend.

- core loads
- content is picked
- config is written
- black screen
- no visible progress
- waited 60+ seconds

Then I use the in-emu F12 menu to choose the disk manually, then do a reset. But still no joy, but a strange `drv:-1` in the log.

My hunch is that somehow the emu is not aware of any disk being loaded on my setup.

- BIOS are confirmed correct hashes.
- keropi/config has been deleted
- retroarch config has been deleted

<details>
<summary>Details</summary>

```
$ /Applications/RetroArch.app/Contents/MacOS/RetroArch ; exit;
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Jan 19 2020
[INFO] Version: 1.8.4
[INFO] =================================================
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] Redirecting save file to "/Users/matt/Documents/RetroArch/saves/.srm".
[INFO] Redirecting savestate to "/Users/matt/Documents/RetroArch/states/.state".
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ 960x720
[INFO] [GL]: Found GL context: cocoagl
[INFO] [GL]: Detecting screen resolution 1920x1155.
[INFO] [GL]: Vendor: Intel Inc., Renderer: Intel HD Graphics 4000 OpenGL Engine.
[INFO] [GL]: Version: 2.1 INTEL-12.10.14.
[INFO] [GL]: Using resolution 960x720
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] Found HID driver: "iohidmanager".
[INFO] [Joypad]: Found joypad driver: "hid".
[INFO] [Video]: Found display server: null
[INFO] [CoreAudio]: Using output sample rate of 48000.0 Hz
[INFO] [CoreAudio]: Using buffer size of 24576 bytes: (latency = 64 ms)
[INFO] [Menu]: Found menu display driver: "gl".
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Menu]: Found menu display driver: "gl".
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [LED]: LED driver = 'null' 0x101223278
[INFO] [MIDI]: Initializing ...
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "null" driver.
[INFO] Disconnecting device from port 1.
[INFO] Disconnecting device from port 2.
[INFO] SRAM will not be saved.
[INFO] Loading history file: [/Users/matt/Library/Application Support/RetroArch/config/content_history.lpl].
[INFO] Loading history file: [/Users/matt/Library/Application Support/RetroArch/config/content_music_history.lpl].
[INFO] Loading history file: [/Users/matt/Library/Application Support/RetroArch/config/content_image_history.lpl].
[INFO] Loading favorites file: [/Users/matt/Library/Application Support/RetroArch/config/content_favorites.lpl].
[INFO] [GL]: VSync => on
[INFO] [GL]: VSync => on
[INFO] Updating firmware status for: /Applications/RetroArch.app/Contents/Resources/cores/px68k_libretro.dylib on /Users/matt/Documents/RetroArch/system
[INFO] Using content: /Users/matt/Downloads/2020-01-23/Akazukin Cha Cha Cha v1.04 (1995)(Sprite).dim.
[INFO] arg #0: retroarch
[INFO] arg #1: /Users/matt/Downloads/2020-01-23/Akazukin Cha Cha Cha v1.04 (1995)(Sprite).dim
[INFO] arg #2: -s
[INFO] arg #3: /Users/matt/Documents/RetroArch/saves
[INFO] arg #4: -S
[INFO] arg #5: /Users/matt/Documents/RetroArch/states
[INFO] arg #6: -c
[INFO] arg #7: /Users/matt/Library/Application Support/RetroArch/config/retroarch.cfg
[INFO] arg #8: -L
[INFO] arg #9: /Applications/RetroArch.app/Contents/Resources/cores/px68k_libretro.dylib
[INFO] arg #10: -v
[INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] Unloading game..
[INFO] Unloading core..
[INFO] Unloading core symbols..
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] Set config file to : /Users/matt/Library/Application Support/RetroArch/config/retroarch.cfg
[INFO] Redirecting save file to "/Users/matt/Documents/RetroArch/saves/Akazukin Cha Cha Cha v1.04 (1995)(Sprite).srm".
[INFO] Redirecting savestate to "/Users/matt/Documents/RetroArch/states/Akazukin Cha Cha Cha v1.04 (1995)(Sprite).state".
[INFO] === Build =======================================
[INFO] CPU Model Name: Intel(R) Core(TM) i7-3540M CPU @ 3.00GHz
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Jan 19 2020
[INFO] Version: 1.8.4
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "/Applications/RetroArch.app/Contents/Resources/cores/px68k_libretro.dylib"
[INFO] [Overrides] no core-specific overrides found at /Users/matt/Library/Application Support/RetroArch/config/PX68K/PX68K.cfg.
[INFO] [Overrides] no content-dir-specific overrides found at /Users/matt/Library/Application Support/RetroArch/config/PX68K/2020-01-23.cfg.
[INFO] [Overrides] no game-specific overrides found at /Users/matt/Library/Application Support/RetroArch/config/PX68K/Akazukin Cha Cha Cha v1.04 (1995)(Sprite).cfg.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] Controller port: 1
[INFO]    RetroPad (ID: 1)
[INFO]    RetroKeyboard (ID: 3)
[INFO] Controller port: 2
[INFO]    RetroPad (ID: 1)
[INFO]    RetroKeyboard (ID: 3)
[INFO] [Environ]: SET_SUPPORT_NO_GAME: yes.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CORE_OPTIONS_INTL.
[INFO] [Remaps]: remap directory: /Users/matt/Library/Application Support/RetroArch/config/remaps
[INFO] Redirecting save file to "/Users/matt/Documents/RetroArch/saves/Akazukin Cha Cha Cha v1.04 (1995)(Sprite).srm".
[INFO] Redirecting savestate to "/Users/matt/Documents/RetroArch/states/Akazukin Cha Cha Cha v1.04 (1995)(Sprite).state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: SYSTEM_DIRECTORY: "/Users/matt/Documents/RetroArch/system".
[INFO] [Environ]: CORE_ASSETS_DIRECTORY: "/Users/matt/Downloads".
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Environ]: SET_DISK_CONTROL_INTERFACE.
[INFO] [Environ]: GET_VARIABLE px68k_joytype1:
	Default (2 Buttons)
[INFO] [Environ]: GET_VARIABLE px68k_joytype2:
	Default (2 Buttons)
[INFO] [Environ]: GET_VARIABLE px68k_cpuspeed:
	10Mhz
[INFO] [Environ]: GET_VARIABLE px68k_ramsize:
	2MB
[INFO] [Environ]: GET_VARIABLE px68k_analog:
	disabled
[INFO] [Environ]: GET_VARIABLE px68k_adpcm_vol:
	15
[INFO] [Environ]: GET_VARIABLE px68k_opm_vol:
	12
[INFO] [Environ]: GET_VARIABLE px68k_disk_drive:
	FDD1
[INFO] [Environ]: GET_VARIABLE px68k_menufontsize:
	normal
[INFO] [Environ]: GET_VARIABLE px68k_joy1_select:
	Default
[INFO] [Environ]: GET_VARIABLE px68k_disk_path:
	enabled
[INFO] [Environ]: GET_VARIABLE px68k_joy_mouse:
	Mouse
[INFO] [Environ]: GET_VARIABLE px68k_vbtn_swap:
	TRIG1 TRIG2
[INFO] [Environ]: GET_VARIABLE px68k_no_wait_mode:
	disabled
[INFO] [Environ]: GET_VARIABLE px68k_frameskip:
	Full Frame
[INFO] Content loading skipped. Implementation will load it on its own.
[libretro INFO] LOAD EMU
[INFO] [RCHEEVOS]: ext_hash 0b886a3f ('dim')
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Cheats]: Load game-specific cheatfile: /Applications/RetroArch.app/Contents/Resources/cht/PX68K/Akazukin Cha Cha Cha v1.04 (1995)(Sprite).cht
[INFO] [RCHEEVOS]: Load task finished
[INFO] [Audio]: Set audio input rate to: 44100.04 Hz.
[INFO] [Video]: Video @ 2400x1800
[INFO] [GL]: Found GL context: cocoagl
[INFO] [GL]: Detecting screen resolution 960x720.
[INFO] [GL]: Vendor: Intel Inc., Renderer: Intel HD Graphics 4000 OpenGL Engine.
[INFO] [GL]: Version: 2.1 INTEL-12.10.14.
[INFO] [GL]: Using resolution 2400x1155
[INFO] [GL]: Default shader backend found: glsl.
[INFO] [Shader driver]: Using GLSL shader backend.
[INFO] [GLSL]: Checking GLSL shader support ...
[WARN] [GL]: Stock GLSL shaders will be used.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GLSL]: Found GLSL vertex shader.
[INFO] [GLSL]: Found GLSL fragment shader.
[INFO] [GLSL]: Linking GLSL program.
[INFO] [GL]: Using 4 textures.
[INFO] [GL]: Loaded 1 program(s).
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Video]: Graphics driver did not initialize an input driver. Attempting to pick a suitable driver.
[INFO] Found HID driver: "iohidmanager".
[INFO] [Joypad]: Found joypad driver: "hid".
[INFO] [Video]: Found display server: null
[INFO] [CoreAudio]: Using output sample rate of 48000.0 Hz
[INFO] [CoreAudio]: Using buffer size of 24576 bytes: (latency = 64 ms)
[INFO] [Menu]: Found menu display driver: "gl".
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [Font]: Using font rendering backend: stb-unicode.
[INFO] [LED]: LED driver = 'null' 0x101223278
[INFO] [MIDI]: Initializing ...
[INFO] [MIDI]: Input disabled.
[INFO] [MIDI]: Output disabled.
[INFO] [MIDI]: Initialized "null" driver.
[INFO] Disconnecting device from port 1.
[libretro INFO] Set Controller Device: 0, Port: 0 0 0
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] Disconnecting device from port 2.
[libretro INFO] Set Controller Device: 0, Port: 1 0 0
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] SRAM will not be saved.
[INFO] Loading history file: [/Users/matt/Library/Application Support/RetroArch/config/content_history.lpl].
[INFO] Loading history file: [/Users/matt/Library/Application Support/RetroArch/config/content_music_history.lpl].
[INFO] Loading history file: [/Users/matt/Library/Application Support/RetroArch/config/content_image_history.lpl].
[INFO] Loading favorites file: [/Users/matt/Library/Application Support/RetroArch/config/content_favorites.lpl].
[INFO] [GL]: VSync => on
[INFO] Written to playlist file: /Users/matt/Library/Application Support/RetroArch/config/content_history.lpl
[libretro INFO] Parsing arguments ...
[libretro INFO] 0 : px68k
[libretro INFO] 1 : /Users/matt/Downloads/2020-01-23/Akazukin Cha Cha Cha v1.04 (1995)(Sprite).dim
[libretro INFO] PX68K Ver."0.15+"
[libretro INFO] Libretro...
[libretro INFO] /Users/matt/Documents/RetroArch/system/keropi
[libretro INFO] cur_dir_str / 1
[libretro INFO] fp:-178925696 (iplrom.dat)
[libretro INFO] R: f800, G: 7e0, B: 1f
[libretro INFO] Restarting PX68K...
[libretro INFO] INIT done
[INFO] [Environ]: GET_VARIABLE px68k_joytype1:
	Default (2 Buttons)
[INFO] [Environ]: GET_VARIABLE px68k_joytype2:
	Default (2 Buttons)
[INFO] [Environ]: GET_VARIABLE px68k_cpuspeed:
	10Mhz
[INFO] [Environ]: GET_VARIABLE px68k_ramsize:
	2MB
[INFO] [Environ]: GET_VARIABLE px68k_analog:
	disabled
[INFO] [Environ]: GET_VARIABLE px68k_adpcm_vol:
	15
[INFO] [Environ]: GET_VARIABLE px68k_opm_vol:
	12
[INFO] [Environ]: GET_VARIABLE px68k_disk_drive:
	FDD1
[INFO] [Environ]: GET_VARIABLE px68k_menufontsize:
	normal
[INFO] [Environ]: GET_VARIABLE px68k_joy1_select:
	Default
[INFO] [Environ]: GET_VARIABLE px68k_disk_path:
	enabled
[INFO] [Environ]: GET_VARIABLE px68k_joy_mouse:
	Mouse
[INFO] [Environ]: GET_VARIABLE px68k_vbtn_swap:
	TRIG1 TRIG2
[INFO] [Environ]: GET_VARIABLE px68k_no_wait_mode:
	disabled
[INFO] [Environ]: GET_VARIABLE px68k_frameskip:
	Full Frame
[libretro INFO] CPU Clock: 10MHz
[libretro INFO] RAM Size: 2MB
[libretro INFO] TextDotX: 768
[libretro INFO] TextDotY: 512
[INFO] SET_GEOMETRY: 768x512, aspect: 1.333.
[libretro INFO] w:768 h:512 a:1.333
[libretro INFO] fps:59.94 soundrate:44100
[INFO] SET_GEOMETRY: 800x600, aspect: 1.333.
[libretro INFO] w:800 h:600 a:1.333
[libretro INFO] fps:59.94 soundrate:44100
[libretro INFO] Restarting PX68K...
[libretro INFO] **** drv:-1 *****
[INFO] [Environ]: SET_GEOMETRY.
[libretro INFO] w:800 h:600 a:1.333
[libretro INFO] fps:59.94 soundrate:44100
[libretro INFO] *** drv:0 ***** / 
[libretro INFO] **** drv:0 *****
[libretro INFO] hoge:0
[libretro INFO] ***** drv:0 *****
[libretro INFO] directory selected: Users
[libretro INFO] *** drv:0 ***** /Users/ 
[libretro INFO] ***** drv:0 *****
[libretro INFO] directory selected: matt
[libretro INFO] *** drv:0 ***** /Users/matt/ 
[libretro INFO] ***** drv:0 *****
[libretro INFO] directory selected: Downloads
[libretro INFO] *** drv:0 ***** /Users/matt/Downloads/ 
[libretro INFO] ***** drv:0 *****
[libretro INFO] directory selected: 2020-01-23
[libretro INFO] *** drv:0 ***** /Users/matt/Downloads/2020-01-23/ 
[libretro INFO] ***** drv:0 *****
[libretro INFO] file selected: Akazukin Cha Cha Cha v1.04 (1995)(Sprite).dim
[libretro INFO] Restarting PX68K...
[libretro INFO] **** drv:-1 *****
[INFO] [config] Saved new config to "/Users/matt/Library/Application Support/RetroArch/config/retroarch.cfg".
[INFO] [Cheats]: Save game-specific cheatfile: /Applications/RetroArch.app/Contents/Resources/cht/PX68K/Akazukin Cha Cha Cha v1.04 (1995)(Sprite).cht
[INFO] Content ran for a total of: 00 hours, 01 minutes, 18 seconds.
[INFO] Unloading game..
[INFO] Unloading core..
[libretro INFO] Retro DeInit
[INFO] Unloading core symbols..
[INFO] [Core Options]: Saved core options file to "/Users/matt/Library/Application Support/RetroArch/config/retroarch-core-options.cfg"
[INFO] [Video]: Average monitor Hz: 59.769291 Hz. (7.816 % frame time deviation, based on 2048 last samples).
[INFO] [Video]: Average monitor Hz: 59.769291 Hz. (7.816 % frame time deviation, based on 2048 last samples).


```
</details>

**Comment by negativeExponent** [comment] 2020-01-24 23:18
i was under the impression you know how to compile the core, so i expected you to know how to bisect to find the bad pr, am i wrong? that was why i offered to look at compiler flags etc since no one atm is able to test on OS X

in any case, did you any other disk that is confirmed to be working? an hdd image perhaps. of drivers are empty and after a reset nothing still happens on the log then something else is stopping core from doing a full loop, coz you would normally see a couple of **buserror:** messaged on log window if so.

hit me up on discord when you have more time to do some tinkering....

**Comment by gingerbeardman** [comment] 2020-01-25 13:18
I have compiled in the past but we have a new baby so my time is non-existant. So sadly I do not have time to dive in to bisect.

A long time ago I was working on a fork with many changes, that was sent to somebody else and they merged many of them. So I definitely have been running and playing the core some time ago.

I've tried many disks, including those I had previously played (mainly golf games and Geograph Seal) and others reported working in other issues (Street Fighter 2). Both floppy and hard.

**Comment by negativeExponent** [comment] 2020-01-27 08:54
life is life, i get that. no one is asking anything here to ignore real life. but im more interested in data and currently this is not leading me to anywhere i can pinpoint or even test with.

**Comment by gingerbeardman** [comment] 2020-01-27 14:23
Agreed, I'll try to get something concrete when I can.

**Comment by negativeExponent** [comment] 2020-01-31 08:34
- ill start with compiler flags. by default (as i stated in a previous closed issue) that the core is compiled with -03 and some extra flags, that may be causing problems. maybe -0O would do something different. Adjusting some OS X flags probably would help as well but dont quote me for that since dunno a thing with makefile and its optimzation/flags
- you can try other file formats (.d88, xcf, or hdd images)
- maybe trap and see what address in cpu writes (wr_main() is it in loop or repeatedly stuck at.
- try compiling older commit
- since the human68k and BIOS has been released as public domain software, here's a human68k boot disk i used which i confirmed to work: 
[Human 68k v3.02 (1993)(Sharp - Hudson).zip](https://github.com/libretro/px68k-libretro/files/4138223/Human.68k.v3.02.1993.Sharp.-.Hudson.zip)

**Comment by gingerbeardman** [comment] 2020-01-31 11:06
Tried the Human 68k image you linked with the default downloaded core: black screen.

Building the core myself - with no changes to libretro-super: success.

![Screen shot 2020-01-31 at 11 04 26](https://user-images.githubusercontent.com/49612/73534648-87b6d980-4419-11ea-93d8-d58cc056c03b.png)

**Comment by negativeExponent** [comment] 2020-01-31 14:00
try to reconfirm (or repeat your previous tests), if self-compiled core DOES worked more times than not compared to the buildbot one... i dont blame if some is wrong with buildbot one, coz at one point, i did notice some issues of core not loading when running the core from online updater.

**Comment by gingerbeardman** [comment] 2020-01-31 16:27
Good idea. The self-built core works with all the games I have been testing. 

Examples:
![Screen shot 2020-01-31 at 16 25 57](https://user-images.githubusercontent.com/49612/73556055-949df200-4446-11ea-9541-9d7cd664e5a1.png)
![Screen shot 2020-01-31 at 16 26 08](https://user-images.githubusercontent.com/49612/73556056-949df200-4446-11ea-9704-930a9c62a76f.png)

![Screen shot 2020-01-31 at 16 26 43](https://user-images.githubusercontent.com/49612/73556058-949df200-4446-11ea-8b17-7acda0642527.png)
![Screen shot 2020-01-31 at 16 26 51](https://user-images.githubusercontent.com/49612/73556059-949df200-4446-11ea-8e8e-87dd3d734892.png)

**Comment by negativeExponent** [comment] 2020-01-31 16:41
ok thanks for the updates. bringing this info to the higher ops, since there is probably something wrong with buildbot core...

**Comment by gingerbeardman** [comment] 2020-01-31 17:14
Glad we finally got there!

**Comment by negativeExponent** [comment] 2020-02-01 15:45
hi. see if the rebuild core now works

**Comment by gingerbeardman** [comment] 2020-02-02 14:55
Still nothing but black screen from the official downloaded core (51ee793)

**Comment by negativeExponent** [comment] 2020-02-02 17:40
ok that's sad, and sadly i cannot do anything more. i've been told that we cannot do drastic changes to how buildbot is currently configured now until its next major overhaul (don't ask me when though)

for now you'll just have to recompile core yourself...

**Comment by gingerbeardman** [comment] 2020-02-02 18:39
I am wondering why it is breaking when compiled on buildbot.

And also if other cores are similarly affected? 

I only use a small set of cores on macOS, so I am unaware of how well they run.

**Comment by negativeExponent** [comment] 2020-02-26 03:40
@gingerbeardman kinda offtopic, but i do recall you had issues with pcsx as well (chd related or something).. can you, if your able to retest with the latest core from buildbot if the problems still persists? and if so, can you recompiled if its still a problem. write a new issue in the pcsx too. thanks.

**Comment by gingerbeardman** [comment] 2020-02-26 12:09
PX68K: 
- Black screen still a problem with latest nightly.
- Self-built core still works.

PCSXRe: 
- Still not working for me at all, with bin/cue.
- Self-built-core also does not work.

**Comment by gingerbeardman** [comment] 2020-04-24 17:37
Still a problem. 😢

**Comment by gphilipp** [comment] 2020-10-01 16:53
I see the same problem, running with Retroarch 1.9.0 and the downloaded core. I tried to build myself the core like @gingerbeardman but it fails with those errors when loading a game:
```
[libretro INFO] BusError: 2ff053e
[libretro INFO] BusError: ff0363
``` 
I tried to build the Jan version (commit `51ee79325a5aa5b3c86e6d62d888c255953fb8dc`), but same result.
Unfortunately it's impossible to download an older version of Retroarch (eg 1.8.4 like @gingerbeardman ). Might have to build it myself I guess.
Unfortunately

**Comment by negativeExponent** [comment] 2020-10-01 21:28
from what i remember about this issue, buildbot core does not run games while when self compiled runs it.

you issue is probably more related to bad rom or rom not loading (or core not loading if run without content) if that bus error appears.

**Comment by gingerbeardman** [comment] 2020-10-02 10:56
I echo what @negativeExponent says

**Comment by gphilipp** [comment] 2020-10-02 11:18
Well, to be sure, I've tested Retroarch 1.8.4 and 1.9.0 on **Windows** with the downloaded core, using the same exact bios files and rom than on my Mac and Gradius II is running fine. No such luck on my Mac. The in-game menu is showing, I can select the files but then it goes black screen when I try to load any game (incl Gradius II). It's definitely a Mac-specific issue.

**Comment by negativeExponent** [comment] 2020-10-02 11:49
> Well, to be sure, I've tested Retroarch 1.8.4 and 1.9.0 on **Windows** with the downloaded core, using the same exact bios files and rom than on my Mac and Gradius II is running fine. No such luck on my Mac. The in-game menu is showing, I can select the files but then it goes black screen when I try to load any game (incl Gradius II). It's definitely a Mac-specific issue.

if you haven't done so already, remove everything on  **<retroarch system folder>/keropi** folder other than **iplrom.dat** and **cgrom.dat**

re-run the game. might be better if you run other confirmed working games as well (hdf perhaps). if still does not play then post or upload your **<retroarch system folder>/keropi/config**

in anycase, since you can run the menu then the issue is not the same as this one as this one deals with core not starting at all when suing core from the buildbot server, but works fine if the core is compiled locally. Might want to start a new thread so it can be tracked better.

**Comment by gingerbeardman** [comment] 2020-10-02 13:37
@negativeExponent with the latest downloaded core it's no longer a blank/black screen but corrupted screens like below. I've not been able to get any game to run in the handful that I have as my test suite.

<img width="1080" alt="Screen shot 2020-10-02 at 14 34 11" src="https://user-images.githubusercontent.com/49612/94929134-9845b500-04bc-11eb-912d-302363100a96.png">

<img width="1080" alt="Screen shot 2020-10-02 at 14 35 08" src="https://user-images.githubusercontent.com/49612/94929151-9b40a580-04bc-11eb-95b0-b9b29949d30f.png">

I do not have time to build the latest source, sorry.

**Comment by gphilipp** [comment] 2020-10-02 15:29
I had this too but I’ve managed to make it work by compiling stuff on my machine.I’m writing up a summary of the combinations which work/don’t work.

**Comment by gingerbeardman** [comment] 2020-10-02 19:51
Awesome! Thanks @gphilipp !

**Comment by negativeExponent** [comment] 2020-10-03 00:48
@gphilipp @gphilipp are you able to get any environment variables, compiler versione etc so we can compare this with buildbot? i wonder if its just the case of old toolkits (im not sure either if the ccache on build was indeed cleared after the incident a few weeks ago)

**Comment by gphilipp** [comment] 2020-10-03 00:49
Actually, after compiling many different versions of Retroarch and the core, I come to the same conclusion as you @gingerbeardman, the downloaded version doesn't work, just need to recompile yourself a core from source and it works with all Retroarch version (i've tested all 1.80+).

**Comment by gphilipp** [comment] 2020-10-03 00:51
> @gphilipp @gphilipp are you able to get any environment variables, compiler versione etc so we can compare this with buildbot? i wonder if its just the case of old toolchains (im not sure either if the ccache on build was indeed cleared after the incident a few weeks ago)

Are there any build logs from buildbot so that can we can compare with what I compile locally?

**Comment by negativeExponent** [comment] 2020-10-03 00:53
buildbot compiled fine. no errors

im just a contributor. if you are interested and can work out the issue you can probably go do our discord channel and coordinate with the people who knows buildbot works and have higher access

**Comment by negativeExponent** [comment] 2021-06-26 04:23
hi if you have the time, can you post full of logfile (debugs on) with buildbot core vs self-compiled one?

thanks

**Comment by gingerbeardman** [comment] 2021-06-28 16:52
I'll try to do this soon

**Comment by gingerbeardman** [comment] 2021-07-12 10:25
testing today buildbot core works OK on macOS for these disks
- Human 68k v3.02 (1993)(Sharp - Hudson).dim
- Akazukin Cha Cha Cha v1.04 (1995)(Sprite).dim (logs below)

buildbot core
925,272 bytes
LOG: [retroarch-buildbot.log](https://github.com/libretro/px68k-libretro/files/6800564/retroarch-buildbot.log)

self-compiled core
912,948 bytes
LOG: [retroarch-selfcompile.log](https://github.com/libretro/px68k-libretro/files/6800565/retroarch-selfcompile.log)

**Closed** 2022-08-30 04:16 UTC
